const { MongoClient } = require("mongodb");

const MONGODB_URI = "mongodb+srv://appuser:AppUser12345@cluste1.h7gpyav.mongodb.net/assis_auth?retryWrites=true&w=majority&appName=Cluste1";

const eventsData = [
  {
    title: "Tech Meetup Bangalore",
    description: "A gathering for tech enthusiasts and developers.",
    emoji: "💻",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "open",
    attendance: null,
    capacity: 100,
    attendees: [],
    pendingRequests: [],
    date: "2026-07-10",
    time: "10:00",
    endDate: "2026-07-10",
    endTime: "14:00",
    timezone: "Asia/Kolkata",
    tags: ["tech", "networking"],
    visibility: "public",
    status: "active",
    location: {
      lat: 12.9715987,
      lng: 77.5945627,
      formattedAddress: "Bangalore, Karnataka, India",
      placeId: "ChIJbU60yXAWrjsR4E9-UejD3_g",
      countryCode: "IN",
      countryName: "India",
      admin1: "Karnataka",
      admin1Code: "KA",
      city: "Bangalore",
      cityKey: "bangalore",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [77.5945627, 12.9715987]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    startsAt: new Date("2026-07-10T04:30:00.000Z"),
    endsAt: new Date("2026-07-10T08:30:00.000Z")
  },
  {
    title: "Yoga Retreat",
    description: "Relax and rejuvenate with our weekend yoga retreat.",
    emoji: "🧘‍♀️",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "paid",
    priceCents: 250000, // 2500 INR
    joinPolicy: "approval",
    attendance: null,
    capacity: 20,
    attendees: [],
    pendingRequests: [],
    date: "2026-08-15",
    time: "07:00",
    endDate: "2026-08-16",
    endTime: "18:00",
    timezone: "Asia/Kolkata",
    tags: ["wellness", "yoga"],
    visibility: "public",
    status: "active",
    location: {
      lat: 30.129037,
      lng: 78.293231,
      formattedAddress: "Rishikesh, Uttarakhand, India",
      placeId: "ChIJK2X4Z8J_DzkR3Hl8mFwQZpI",
      countryCode: "IN",
      countryName: "India",
      admin1: "Uttarakhand",
      admin1Code: "UK",
      city: "Rishikesh",
      cityKey: "rishikesh",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [78.293231, 30.129037]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    startsAt: new Date("2026-08-15T01:30:00.000Z"),
    endsAt: new Date("2026-08-16T12:30:00.000Z")
  },
  {
    title: "Photography Walk",
    description: "Explore the old city and capture street photography.",
    emoji: "📸",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "open",
    attendance: null,
    capacity: 15,
    attendees: [],
    pendingRequests: [],
    date: "2026-06-30",
    time: "16:00",
    endDate: "2026-06-30",
    endTime: "19:00",
    timezone: "Asia/Kolkata",
    tags: ["photography", "art"],
    visibility: "public",
    status: "active",
    location: {
      lat: 28.6139391,
      lng: 77.2090212,
      formattedAddress: "New Delhi, Delhi, India",
      placeId: "ChIJLbZ-kq09DzQRO1ev11k4J4A",
      countryCode: "IN",
      countryName: "India",
      admin1: "Delhi",
      admin1Code: "DL",
      city: "New Delhi",
      cityKey: "new delhi",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [77.2090212, 28.6139391]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    startsAt: new Date("2026-06-30T10:30:00.000Z"),
    endsAt: new Date("2026-06-30T13:30:00.000Z")
  },
  {
    title: "Gourmet Cooking Class",
    description: "Learn to cook authentic Italian cuisine.",
    emoji: "🍝",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "paid",
    priceCents: 150000,
    joinPolicy: "open",
    attendance: null,
    capacity: 10,
    attendees: [],
    pendingRequests: [],
    date: "2026-07-05",
    time: "11:00",
    endDate: "2026-07-05",
    endTime: "14:00",
    timezone: "Asia/Kolkata",
    tags: ["food", "cooking"],
    visibility: "public",
    status: "active",
    location: {
      lat: 19.0760,
      lng: 72.8777,
      formattedAddress: "Mumbai, Maharashtra, India",
      placeId: "ChIJwe1EZjDG5zsRaYxkjY_tpF0",
      countryCode: "IN",
      countryName: "India",
      admin1: "Maharashtra",
      admin1Code: "MH",
      city: "Mumbai",
      cityKey: "mumbai",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [72.8777, 19.0760]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1556910103-1c02745a872f?w=800&q=80",
    startsAt: new Date("2026-07-05T05:30:00.000Z"),
    endsAt: new Date("2026-07-05T08:30:00.000Z")
  },
  {
    title: "Live Indie Music",
    description: "Local indie bands performing live.",
    emoji: "🎸",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "open",
    attendance: null,
    capacity: 50,
    attendees: [],
    pendingRequests: [],
    date: "2026-07-12",
    time: "19:00",
    endDate: "2026-07-12",
    endTime: "23:00",
    timezone: "Asia/Kolkata",
    tags: ["music", "concert"],
    visibility: "public",
    status: "active",
    location: {
      lat: 18.5204,
      lng: 73.8567,
      formattedAddress: "Pune, Maharashtra, India",
      placeId: "ChIJARFGZy6_wjsRQ-Oenb9Osbg",
      countryCode: "IN",
      countryName: "India",
      admin1: "Maharashtra",
      admin1Code: "MH",
      city: "Pune",
      cityKey: "pune",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [73.8567, 18.5204]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    startsAt: new Date("2026-07-12T13:30:00.000Z"),
    endsAt: new Date("2026-07-12T17:30:00.000Z")
  },
  {
    title: "Startup Pitch Night",
    description: "Entrepreneurs pitch their ideas to investors.",
    emoji: "🚀",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "paid",
    priceCents: 50000,
    joinPolicy: "approval",
    attendance: null,
    capacity: 80,
    attendees: [],
    pendingRequests: [],
    date: "2026-07-20",
    time: "18:00",
    endDate: "2026-07-20",
    endTime: "21:00",
    timezone: "Asia/Kolkata",
    tags: ["startup", "business"],
    visibility: "public",
    status: "active",
    location: {
      lat: 17.3850,
      lng: 78.4867,
      formattedAddress: "Hyderabad, Telangana, India",
      placeId: "ChIJx9Lr6tqZyzsRwvu6G4Zk_fA",
      countryCode: "IN",
      countryName: "India",
      admin1: "Telangana",
      admin1Code: "TG",
      city: "Hyderabad",
      cityKey: "hyderabad",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [78.4867, 17.3850]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80",
    startsAt: new Date("2026-07-20T12:30:00.000Z"),
    endsAt: new Date("2026-07-20T15:30:00.000Z")
  },
  {
    title: "Art Exhibition",
    description: "Modern art exhibition by local artists.",
    emoji: "🎨",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "open",
    attendance: null,
    capacity: null,
    attendees: [],
    pendingRequests: [],
    date: "2026-08-01",
    time: "10:00",
    endDate: "2026-08-05",
    endTime: "18:00",
    timezone: "Asia/Kolkata",
    tags: ["art", "culture"],
    visibility: "public",
    status: "active",
    location: {
      lat: 22.5726,
      lng: 88.3639,
      formattedAddress: "Kolkata, West Bengal, India",
      placeId: "ChIJZ_b1q-q6wTsRqY5lKqP2L2A",
      countryCode: "IN",
      countryName: "India",
      admin1: "West Bengal",
      admin1Code: "WB",
      city: "Kolkata",
      cityKey: "kolkata",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [88.3639, 22.5726]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80",
    startsAt: new Date("2026-08-01T04:30:00.000Z"),
    endsAt: new Date("2026-08-05T12:30:00.000Z")
  },
  {
    title: "Web3 Hackathon",
    description: "Build the next generation of decentralized apps.",
    emoji: "🌐",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "approval",
    attendance: null,
    capacity: 200,
    attendees: [],
    pendingRequests: [],
    date: "2026-08-10",
    time: "09:00",
    endDate: "2026-08-12",
    endTime: "17:00",
    timezone: "Asia/Kolkata",
    tags: ["hackathon", "crypto"],
    visibility: "public",
    status: "active",
    location: {
      lat: 13.0827,
      lng: 80.2707,
      formattedAddress: "Chennai, Tamil Nadu, India",
      placeId: "ChIJYTN9T-plUjoRM9RjaAunYW4",
      countryCode: "IN",
      countryName: "India",
      admin1: "Tamil Nadu",
      admin1Code: "TN",
      city: "Chennai",
      cityKey: "chennai",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [80.2707, 13.0827]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    startsAt: new Date("2026-08-10T03:30:00.000Z"),
    endsAt: new Date("2026-08-12T11:30:00.000Z")
  },
  {
    title: "Hiking Expedition",
    description: "A scenic day hike in the mountains.",
    emoji: "🥾",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "paid",
    priceCents: 120000,
    joinPolicy: "open",
    attendance: null,
    capacity: 25,
    attendees: [],
    pendingRequests: [],
    date: "2026-09-05",
    time: "06:00",
    endDate: "2026-09-05",
    endTime: "16:00",
    timezone: "Asia/Kolkata",
    tags: ["outdoor", "hiking"],
    visibility: "public",
    status: "active",
    location: {
      lat: 31.1048,
      lng: 77.1734,
      formattedAddress: "Shimla, Himachal Pradesh, India",
      placeId: "ChIJw2w2iW_xDDkRO-1d2Zl065g",
      countryCode: "IN",
      countryName: "India",
      admin1: "Himachal Pradesh",
      admin1Code: "HP",
      city: "Shimla",
      cityKey: "shimla",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [77.1734, 31.1048]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1551632811-561f31d17d5c?w=800&q=80",
    startsAt: new Date("2026-09-05T00:30:00.000Z"),
    endsAt: new Date("2026-09-05T10:30:00.000Z")
  },
  {
    title: "Film Screening",
    description: "Screening of classic world cinema.",
    emoji: "🎬",
    creatorClerkId: "user_3FOqIsfDzA3Hh8Q05yt25IgQdNc",
    creatorName: "Soumya",
    kind: "free",
    priceCents: null,
    joinPolicy: "open",
    attendance: null,
    capacity: 100,
    attendees: [],
    pendingRequests: [],
    date: "2026-07-28",
    time: "18:00",
    endDate: "2026-07-28",
    endTime: "21:00",
    timezone: "Asia/Kolkata",
    tags: ["movie", "entertainment"],
    visibility: "public",
    status: "active",
    location: {
      lat: 23.0225,
      lng: 72.5714,
      formattedAddress: "Ahmedabad, Gujarat, India",
      placeId: "ChIJ2e2-04n0XjkR74XpY4_0e-8",
      countryCode: "IN",
      countryName: "India",
      admin1: "Gujarat",
      admin1Code: "GJ",
      city: "Ahmedabad",
      cityKey: "ahmedabad",
      postalCode: "",
      neighborhood: "",
      source: "places_autocomplete",
      geo: {
        type: "Point",
        coordinates: [72.5714, 23.0225]
      }
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    bannerUri: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    startsAt: new Date("2026-07-28T12:30:00.000Z"),
    endsAt: new Date("2026-07-28T15:30:00.000Z")
  }
];

async function seed() {
  console.log("Connecting to MongoDB...");
  const client = new MongoClient(MONGODB_URI);
  try {
    await client.connect();
    const db = client.db("assis_auth");
    const result = await db.collection("events").insertMany(eventsData);
    console.log(`Successfully inserted ${result.insertedCount} events.`);
  } catch (error) {
    console.error("Error inserting events:", error);
  } finally {
    await client.close();
  }
}

seed();
